# Generated by Django 5.1.6 on 2025-05-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField(choices=[(1, '1st Class'), (2, '2nd Class'), (3, '3rd Class')], verbose_name='Passenger Class')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], verbose_name='Gender')),
                ('age', models.FloatField(verbose_name='Age')),
                ('sibsp', models.IntegerField(verbose_name='Siblings/Spouse Aboard')),
                ('parch', models.IntegerField(verbose_name='Parents/Children Aboard')),
                ('fare', models.FloatField(verbose_name='Fare')),
                ('embarked', models.CharField(choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1, verbose_name='Port of Embarkation')),
                ('survived', models.BooleanField(null=True, verbose_name='Survived')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Titanic Passenger',
                'verbose_name_plural': 'Titanic Passengers',
            },
        ),
    ]
